### PR TITLE
add emmet

### PR DESCRIPTION
**Pull request by Steffan153**
So you can close this if you don't want it, but here you go if you do.
Screen Capture_select-area_20201119123702

### CODE REVIEW

**Comment by Conner1115** [comment]
Nice, man!  I'll add this for sure!

**Comment by Conner1115** [comment]
How did you make that GIF?

**Comment by Steffan153** [comment]
Normal screen recorder?

**Comment by Conner1115** [comment]
Can you show me how to do that?
I don't know how to do a screen recording.

**Comment by Steffan153** [comment]
Ugh, what OS do you use?

**Comment by Conner1115** [comment]
I use a macOS Catalina.  Is the recording under the Developer Tools tab in
the Performance Tab?

**Comment by Steffan153** [comment]
No lmaoooo that's to record performance.

See https://support.apple.com/en-us/HT208721 . (why not google?)

**Comment by Conner1115** [comment]
Thanks, I'll check it out.

**Comment by Conner1115** [comment]
Sorry to bother you again, but I was able to record but not turn it into a
GIF.

**Comment by Steffan153** [comment]
Smh I don't even have a Mac. Just google how to convert it to a gif.

**Comment by Conner1115** [comment]
Got it.

**Pull request merged**
